// src/components/metadata-display.tsx
"use client";

import type { YouTubeVideo } from "@/app/actions";
import Image from "next/image";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

// Import required icons for improved UI and feature richness
import { 
  Calendar, FileText, Tags, User, Image as ImageIcon, 
  Clipboard, Check, RefreshCcw, Eye, ThumbsUp, Info, 
  FileSignature, Link, Download, Copy
} from "lucide-react"; 

import React from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator"; 
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"; // Assuming Tooltip component exists

// Define a structured component for copying text to enhance code structure and readability
const CopyButton = ({ textToCopy, label, icon: Icon, successMessage }: { textToCopy: string, label: string, icon: React.ElementType, successMessage: string }) => {
    const { toast } = useToast();
    const [copied, setCopied] = React.useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(textToCopy);
        setCopied(true);
        toast({
            title: "Copied!",
            description: successMessage,
            duration: 2000,
        });
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <TooltipProvider>
            <Tooltip delayDuration={300}>
                <TooltipTrigger asChild>
                    <Button variant="ghost" size="sm" onClick={handleCopy} className="p-2 h-auto text-sm">
                        {copied ? <Check className="h-4 w-4 text-green-500" /> : <Icon className="h-4 w-4 mr-1" />}
                        {copied ? "Copied" : label}
                    </Button>
                </TooltipTrigger>
                <TooltipContent>
                    <p>Click to copy the {label.toLowerCase()} text.</p>
                </TooltipContent>
            </Tooltip>
        </TooltipProvider>
    );
};
// ------------------------------------------------------------------------------------------------------


interface MetadataDisplayProps {
  data: YouTubeVideo;
  onNewUrl: () => void;
}

export function MetadataDisplay({ data, onNewUrl }: MetadataDisplayProps) {
  // Destructure all available data points for clarity
  const { snippet, viewCount, likeCount, videoId } = data; 
  const { toast } = useToast();
  
  // Format the publication date for better user experience
  const publishedDate = new Date(snippet.publishedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Construct the full text to copy, ensuring structured and complete output
  const fullMetadataTextToCopy = `
*** YouTube Metadata Analysis for Video ID: ${videoId} ***

Title: ${snippet.title}
Channel: ${snippet.channelTitle}
Published Date: ${publishedDate}
Video URL: https://www.youtube.com/watch?v=${videoId}
${viewCount ? `Total Views: ${viewCount.toLocaleString()}` : ''}
${likeCount ? `Total Likes: ${likeCount.toLocaleString()}` : ''}

--- Description ---
${snippet.description}

--- Tags (Keywords) ---
${(snippet.tags || []).join(', ')}

[Generated by MetaTube Inspector]
`.trim();

    const handleFullCopy = () => {
        // Main function to copy all structured data
        navigator.clipboard.writeText(fullMetadataTextToCopy);
        toast({
            title: "Success! All Data Copied.",
            description: "The complete structured metadata report has been copied to your clipboard.",
            duration: 3000,
        });
    };

  return (
    // Main Card container with enhanced shadow and styling
    <Card className="w-full max-w-5xl animate-fade-in shadow-2xl border-2 border-primary/20 text-left bg-white dark:bg-gray-800">
      
      {/* --- Card Header: Title, Actions, and Summary Stats --- */}
      <CardHeader className="flex flex-col gap-4 p-6">
          <div className="flex justify-between items-start gap-4">
              <div className="flex-1">
                  {/* Primary Video Title */}
                  <h2 className="text-3xl font-extrabold tracking-tight text-primary leading-tight">
                    {snippet.title}
                  </h2>
                  {/* Video URL Button */}
                  <a 
                    href={`https://www.youtube.com/watch?v=${videoId}`} 
                    target="_blank" 
                    rel="noopener noreferrer" 
                    className="inline-flex items-center text-sm text-blue-500 hover:text-blue-700 transition-colors mt-1"
                  >
                    <Link className="h-4 w-4 mr-1" />
                    View Original Video
                  </a>
              </div>
              
              {/* Action Buttons */}
              <div className="flex gap-2 shrink-0">
                  <TooltipProvider>
                      <Tooltip delayDuration={300}>
                          <TooltipTrigger asChild>
                              {/* Main Copy Button */}
                              <Button 
                                  variant="default" 
                                  size="icon" 
                                  onClick={handleFullCopy} 
                                  aria-label="Copy full metadata report" 
                                  className="transition-colors duration-300 bg-green-600 hover:bg-green-700"
                              >
                                  <Clipboard className="h-5 w-5" />
                              </Button>
                          </TooltipTrigger>
                          <TooltipContent>
                              <p>Copy Full Structured Metadata Report (Title, Stats, Desc, Tags)</p>
                          </TooltipContent>
                      </Tooltip>
                  </TooltipProvider>

                  <TooltipProvider>
                      <Tooltip delayDuration={300}>
                          <TooltipTrigger asChild>
                              {/* New Search Button */}
                              <Button 
                                  variant="outline" 
                                  size="icon" 
                                  onClick={onNewUrl} 
                                  aria-label="Start new search" 
                                  className="transition-colors duration-300 hover:bg-red-500 hover:text-white"
                              >
                                  <RefreshCcw className="h-5 w-5" />
                              </Button>
                          </TooltipTrigger>
                          <TooltipContent>
                              <p>Start New Metadata Search</p>
                          </TooltipContent>
                      </Tooltip>
                  </TooltipProvider>
              </div>
          </div>

          <Separator className="my-2" /> 

          {/* Enhanced Metadata Summary Row: Key Information */}
          <div className="flex flex-wrap items-center gap-x-6 gap-y-3 pt-1 text-sm text-gray-600 dark:text-gray-400 font-medium">
              
              {/* Channel Badge */}
              <Badge variant="secondary" className="px-3 py-1 flex items-center gap-2 text-base bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200 shadow-sm">
                  <User className="h-4 w-4" />
                  <span className="font-semibold">{snippet.channelTitle}</span>
              </Badge>
              
              {/* Publish Date Badge */}
              <Badge variant="secondary" className="px-3 py-1 flex items-center gap-2 text-base shadow-sm">
                  <Calendar className="h-4 w-4" />
                  <span>Published: {publishedDate}</span>
              </Badge>

              {/* Views Count Badge */}
              {viewCount && (
                  <Badge variant="secondary" className="px-3 py-1 flex items-center gap-2 text-base bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200 shadow-sm">
                      <Eye className="h-4 w-4" />
                      <span>Views: **{viewCount.toLocaleString()}**</span>
                  </Badge>
              )}
              
              {/* Likes Count Badge */}
              {likeCount && (
                  <Badge variant="secondary" className="px-3 py-1 flex items-center gap-2 text-base bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200 shadow-sm">
                      <ThumbsUp className="h-4 w-4" />
                      <span>Likes: {likeCount.toLocaleString()}</span>
                  </Badge>
              )}

              {/* Video ID Badge */}
               <Badge variant="secondary" className="px-3 py-1 flex items-center gap-2 text-base">
                  <FileSignature className="h-4 w-4" />
                  <span>ID: {videoId}</span>
              </Badge>
          </div>
      </CardHeader>

      {/* --- Card Content: Accordions for Detailed Data --- */}
      <CardContent className="p-6 pt-0">
        
        {/* Accordion Setup */}
        <Accordion type="multiple" defaultValue={["item-1", "item-2", "item-3"]} className="w-full space-y-4">
            
            {/* 1. Thumbnails Section */}
            <AccordionItem value="item-1" className="border-b-2 border-primary/10 rounded-lg shadow-md hover:shadow-lg transition-shadow">
                <AccordionTrigger className="hover:no-underline px-4 py-3 bg-primary/5 rounded-t-lg data-[state=open]:bg-primary/10 transition-colors">
                    <h3 className="text-xl font-bold flex items-center gap-3 text-primary">
                        <ImageIcon className="h-6 w-6" /> Thumbnails ({Object.keys(snippet.thumbnails).length})
                        <Info className="h-4 w-4 text-gray-500 ml-2" />
                    </h3>
                </AccordionTrigger>
                <AccordionContent className="p-4 bg-secondary/10 rounded-b-lg">
                    {/* Content Description for SEO/Context */}
                    <p className="text-sm text-muted-foreground mb-4">
                        These images represent different resolutions of the video thumbnail, crucial for **SEO (Search Engine Optimization)** and social sharing previews. Higher resolutions like **Max-Res (1280x720)** are best for display. Click any thumbnail to open the direct image link.
                    </p>
                    <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4 pt-2">
                        {/* Thumbnail Images Mapping */}
                        {snippet.thumbnails.maxres && <ThumbnailImage title="Max-Res" src={snippet.thumbnails.maxres.url} />}
                        {snippet.thumbnails.standard && <ThumbnailImage title="Standard" src={snippet.thumbnails.standard.url} />}
                        <ThumbnailImage title="High" src={snippet.thumbnails.high.url} />
                        <ThumbnailImage title="Medium" src={snippet.thumbnails.medium.url} />
                        <ThumbnailImage title="Default" src={snippet.thumbnails.default.url} />
                    </div>
                </AccordionContent>
            </AccordionItem>
            
            {/* 2. Description Section */}
            {snippet.description && (
            <AccordionItem value="item-2" className="border-b-2 border-primary/10 rounded-lg shadow-md hover:shadow-lg transition-shadow">
                <AccordionTrigger className="hover:no-underline px-4 py-3 bg-primary/5 rounded-t-lg data-[state=open]:bg-primary/10 transition-colors">
                    <h3 className="text-xl font-bold flex items-center gap-3 text-primary">
                        <FileText className="h-6 w-6" /> Description 
                        <span className="text-base font-normal text-gray-600">({snippet.description.length} Characters)</span>
                    </h3>
                    <div className="mr-4 shrink-0">
                        {/* Specific Copy Button for Description */}
                         <CopyButton 
                            textToCopy={snippet.description} 
                            label="Copy Description" 
                            icon={Copy} 
                            successMessage="Description copied successfully."
                        />
                    </div>
                </AccordionTrigger>
                <AccordionContent className="p-4 bg-secondary/10 rounded-b-lg">
                    {/* Content Description for SEO/Context */}
                    <p className="text-sm text-muted-foreground mb-4">
                        The description is vital for YouTube's algorithm and user engagement. It should contain relevant **long-tail keywords** and clear calls-to-action (CTAs). The word count and keyword density are key factors in ranking.
                    </p>
                    <div className="max-h-96 overflow-y-auto whitespace-pre-wrap rounded-lg bg-white dark:bg-gray-900 p-4 text-card-foreground/90 font-sans text-sm border border-gray-300 shadow-inner">
                        {snippet.description}
                    </div>
                </AccordionContent>
            </AccordionItem>
            )}
            
            {/* 3. Tags Section */}
            {snippet.tags && snippet.tags.length > 0 && (
            <AccordionItem value="item-3" className="border-b-2 border-primary/10 rounded-lg shadow-md hover:shadow-lg transition-shadow">
                <AccordionTrigger className="hover:no-underline px-4 py-3 bg-primary/5 rounded-t-lg data-[state=open]:bg-primary/10 transition-colors">
                    <h3 className="text-xl font-bold flex items-center gap-3 text-primary">
                        <Tags className="h-6 w-6" /> Tags ({snippet.tags.length})
                        <Info className="h-4 w-4 text-gray-500 ml-2" />
                    </h3>
                    <div className="mr-4 shrink-0">
                        {/* Specific Copy Button for Tags */}
                        <CopyButton 
                            textToCopy={snippet.tags.join(', ')} 
                            label="Copy Tags (CSV)" 
                            icon={Copy} 
                            successMessage="Tags copied in CSV format."
                        />
                    </div>
                </AccordionTrigger>
                <AccordionContent className="p-4 bg-secondary/10 rounded-b-lg">
                    {/* Content Description for SEO/Context */}
                    <p className="text-sm text-muted-foreground mb-4">
                        Tags help categorize the video and broaden its reach. These are the keywords used by the creator. Use a mix of broad and specific terms.
                    </p>
                    <div className="flex flex-wrap gap-2 pt-2">
                        {snippet.tags.map(tag => (
                            <Badge key={tag} variant="default" className="font-medium text-base px-3 py-1 bg-purple-600 hover:bg-purple-700 text-white shadow-md">
                                {tag}
                            </Badge>
                        ))}
                    </div>
                </AccordionContent>
            </AccordionItem>
            )}
        </Accordion>
      </CardContent>
      {/* Footer for additional context */}
      <div className="p-4 border-t text-xs text-center text-muted-foreground">
          <p>
              Disclaimer: This metadata is retrieved directly from the YouTube Data API. Some fields may be empty if the creator did not provide them. 
              Always check the official video page for the most up-to-date information.
          </p>
      </div>
    </Card>
  );
}

// Separate component for Thumbnail Image display and download functionality
function ThumbnailImage({ src, title }: { src: string; title: string }) {
    return (
        <a href={src} target="_blank" rel="noopener noreferrer" className="group relative overflow-hidden rounded-lg block shadow-md hover:shadow-xl transition-shadow">
            <Image
                src={src}
                alt={`${title} thumbnail`}
                width={480}
                height={360}
                style={{ aspectRatio: '4/3' }}
                className="w-full h-full object-cover border-2 border-border group-hover:border-primary/80 group-hover:scale-105 transition-all duration-300"
                unoptimized
            />
            {/* Overlay with Download Link */}
            <div className="absolute inset-0 flex items-center justify-center bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <TooltipProvider>
                    <Tooltip delayDuration={100}>
                        <TooltipTrigger asChild>
                            <a 
                                href={src} 
                                download={`${title}_thumbnail.jpg`} 
                                onClick={(e) => e.stopPropagation()} 
                                className="bg-white/90 text-gray-900 p-2 rounded-full hover:bg-white transition-colors"
                            >
                                <Download className="h-5 w-5" />
                            </a>
                        </TooltipTrigger>
                        <TooltipContent>
                            <p>Download {title}</p>
                        </TooltipContent>
                    </Tooltip>
                </TooltipProvider>
            </div>
             {/* Title Display at the bottom */}
            <div className="absolute bottom-0 left-0 right-0 p-1 text-white text-xs text-center font-bold bg-black/70">
                {title}
            </div>
        </a>
    )
                    }
